server {
    listen 80;
    server_name meusite.com www.meusite.com;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name meusite.com www.meusite.com;

    ssl_certificate /etc/nginx/certs/site.crt;
    ssl_certificate_key /etc/nginx/certs/site.key;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}